### ISSUE TITLE
Uncaught KeyError: 'ssh'


### ISSUE THREAD

**Issue by pigreco** [akbargumbira/qgis_resources_sharing#52]
Steps to reproduce
 1. First 
 2. Second 
 3. Third 

```
Traceback (most recent call last):
  File "C:/Users/Salvatore/.qgis2/python/plugins\qgis_resources_sharing\resource_sharing\collection_manager.py", line 43, in run
    self._collection_id)
  File "C:/Users/Salvatore/.qgis2/python/plugins\qgis_resources_sharing\resource_sharing\collection_manager.py", line 139, in download
    collection_id, register_name)
  File "C:/Users/Salvatore/.qgis2/python/plugins\qgis_resources_sharing\resource_sharing\repository_handler\remote_git_handler.py", line 130, in download_collection
    if self.url.encode('utf-8') == git_parsed.url2ssh:
  File "C:/Users/Salvatore/.qgis2/python/plugins\qgis_resources_sharing\ext_libs\giturlparse\result.py", line 68, in url2ssh
    return self.format('ssh')
  File "C:/Users/Salvatore/.qgis2/python/plugins\qgis_resources_sharing\ext_libs\giturlparse\result.py", line 54, in format
    return self._platform_obj.FORMATS[protocol] % self._parsed
KeyError: 'ssh'

```
qgis_resources_sharing 0.5.1, QGIS 2.18.14 on Windows 10

**Comment by havatv** [comment]
Hi, @pigreco. This issue is getting rather old. It would be nice if you could test the latest version of the plugin with QGIS 3.4 or QGIS 3.10, and see if the problem persists.

**Comment by pigreco** [comment]
> Ciao @pigreco . Questo problema sta diventando piuttosto vecchio. Sarebbe bello se potessi testare l'ultima versione del plugin con QGIS 3.4 o QGIS 3.10 e vedere se il problema persiste.

everything ok on 3.4 and 3.10
close
